name: first github action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world!'
      - run: echo 'this is step'
  print-hello-world2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world2!'
      - run: echo 'this is step2'
