name: first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install node modules
        run: yarn
      - name: build project
        run: yarn build
      - name: setup finish
        run: echo 'hurray'
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - run: echo 'testing'
